import { useEffect, useMemo, useState } from 'react'
import { APPROVED_IMAGES } from './approved-images'
import recipesCsv from '../project-assets/recipes.csv?raw'
import ingredientsCsv from '../project-assets/ingredients.csv?raw'
import recipeIngredientsCsv from '../project-assets/recipe_ingredients.csv?raw'
import stepsCsv from '../project-assets/recipe_steps.csv?raw'
import cuisinesCsv from '../project-assets/cuisines.csv?raw'
import mealTypesCsv from '../project-assets/meal_types.csv?raw'
import dietaryCsv from '../project-assets/dietary_tags.csv?raw'
import categoriesCsv from '../project-assets/recipe_categories.csv?raw'
import unitsCsv from '../project-assets/units.csv?raw'

const Icon = ({ name, size = 18 }) => {
  const paths = {
    book: <><path d="M4 3h11a3 3 0 0 1 3 3v15H7a3 3 0 0 1-3-3V3Z"/><path d="M7 17h11M8 7h6M8 11h5"/></>,
    calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,
    cart: <><path d="M3 3h2l2.4 11.5a2 2 0 0 0 2 1.5h7.8a2 2 0 0 0 2-1.6L21 7H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></>,
    plus: <path d="M12 5v14M5 12h14"/>, search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.8M16 3.2a4 4 0 0 1 0 7.6"/></>,
    chevron: <path d="m9 18 6-6-6-6"/>, close: <path d="m6 6 12 12M18 6 6 18"/>, more: <><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></>,
    trash: <><path d="M4 7h16M9 11v6M15 11v6M6 7l1 14h10l1-14M9 7V4h6v3"/></>, grip: <path d="M9 5h.01M15 5h.01M9 12h.01M15 12h.01M9 19h.01M15 19h.01"/>,
    check: <path d="m5 12 4 4L19 6"/>, arrow: <path d="m15 18-6-6 6-6"/>, flame: <path d="M12 22c4 0 7-3 7-7 0-3-2-6-5-9 0 3-2 4-3 5 0-4-2-7-2-7s-4 5-4 11c0 4 3 7 7 7Z"/>,
    upload: <><path d="M12 16V4M7 9l5-5 5 5"/><path d="M5 14v6h14v-6"/></>, sliders: <><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="8" cy="18" r="2"/></>
  }
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>
}

function parseCSV(text) {
  const rows = []; let row = [], cell = '', quoted = false
  for (let i = 0; i < text.length; i++) { const c = text[i], n = text[i + 1]
    if (c === '"' && quoted && n === '"') { cell += '"'; i++ }
    else if (c === '"') quoted = !quoted
    else if (c === ',' && !quoted) { row.push(cell); cell = '' }
    else if ((c === '\n' || c === '\r') && !quoted) { if (c === '\r' && n === '\n') i++; row.push(cell); if (row.some(Boolean)) rows.push(row); row = []; cell = '' }
    else cell += c
  }
  if (cell || row.length) { row.push(cell); rows.push(row) }
  const [headers, ...data] = rows
  return data.map(r => Object.fromEntries(headers.map((h, i) => [h.trim(), (r[i] || '').trim()])))
}

const lookups = {
  cuisines: parseCSV(cuisinesCsv), mealTypes: parseCSV(mealTypesCsv), dietary: parseCSV(dietaryCsv),
  categories: parseCSV(categoriesCsv), ingredients: parseCSV(ingredientsCsv), units: parseCSV(unitsCsv)
}
const ingRows = parseCSV(recipeIngredientsCsv), stepRows = parseCSV(stepsCsv)
const seedRecipes = parseCSV(recipesCsv).map(r => ({ ...r, servings: +r.servings, prep: +r.prep_time_minutes, cook: +r.cook_time_minutes,
  spice: +r.spice_level_0_to_5, cuisine: r.cuisine_id, mealType: r.meal_type_id, dietary: r.dietary_tag_ids.split(',').filter(Boolean), categories: r.category_ids.split(',').filter(Boolean), accent: r.accent_color,
  image: r.cover_image_url, includeSuggestions: r.include_in_meal_suggestions === 'true', includeShopping: true, showNutrition: false, substitutions: true, measurement: 'US',
  ingredients: ingRows.filter(i => i.recipe_id === r.recipe_id).map(i => ({...i, optional: i.optional === 'True'})),
  steps: stepRows.filter(s => s.recipe_id === r.recipe_id).map(s => ({text:s.instruction, timer:+s.timer_minutes})) }))

const days = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'], slots = ['Breakfast','Lunch','Dinner','Snack']
const colors = ['#DE6B48','#D99B3D','#6E8B66','#557D8B','#765B8B','#C06470']
const idName = (list, id, idKey, nameKey) => list.find(x => x[idKey] === id)?.[nameKey] || id
const localDate = d => { const x = new Date(d); x.setMinutes(x.getMinutes() - x.getTimezoneOffset()); return x.toISOString().slice(0,10) }
const mondayOf = (d = new Date()) => { const x = new Date(d); const day = x.getDay() || 7; x.setDate(x.getDate() - day + 1); x.setHours(0,0,0,0); return x }
const load = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback } catch { return fallback } }

function App() {
  const [view,setView] = useState('recipes'), [userRecipes,setUserRecipes] = useState(()=>load('hearth-recipes',[]))
  const [plan,setPlan] = useState(()=>load('hearth-plan',{})), [checked,setChecked] = useState(()=>load('hearth-checked',{}))
  const [pantry,setPantry] = useState(()=>load('hearth-pantry',{})), [selected,setSelected] = useState(null)
  const [search,setSearch] = useState(''), [week,setWeek] = useState(()=>localDate(mondayOf())), [plannerPick,setPlannerPick] = useState(null)
  const recipes = useMemo(()=>[...seedRecipes,...userRecipes],[userRecipes])
  useEffect(()=>localStorage.setItem('hearth-recipes',JSON.stringify(userRecipes)),[userRecipes])
  useEffect(()=>localStorage.setItem('hearth-plan',JSON.stringify(plan)),[plan])
  useEffect(()=>localStorage.setItem('hearth-checked',JSON.stringify(checked)),[checked])
  useEffect(()=>localStorage.setItem('hearth-pantry',JSON.stringify(pantry)),[pantry])
  const weekDates = useMemo(()=>days.map((_,i)=>{const d=new Date(`${week}T12:00:00`);d.setDate(d.getDate()+i);return d}),[week])
  const navigate = v => { setView(v); setSelected(null); window.scrollTo(0,0) }
  const assign = (date,slot,id) => { const key=`${localDate(date)}|${slot}`; setPlan(p=>({...p,[key]:id})); setPlannerPick(null) }
  const shiftWeek = n => { const d=new Date(`${week}T12:00:00`); d.setDate(d.getDate()+n*7); setWeek(localDate(d)) }
  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>navigate('recipes')}><span className="brandmark">H</span><span>Hearth<span>&amp;</span>Table</span></button>
      <nav>{[['recipes','book','Recipes'],['planner','calendar','Meal Planner'],['shopping','cart','Shopping List']].map(([v,i,l])=><button key={v} className={view===v?'active':''} onClick={()=>navigate(v)}><Icon name={i}/>{l}</button>)}</nav>
      <button className="new-recipe" onClick={()=>navigate('new')}><Icon name="plus"/> New recipe</button>
    </header>
    <main>
      {view==='recipes' && !selected && <Catalog recipes={recipes} search={search} setSearch={setSearch} open={setSelected} add={()=>navigate('new')}/>}
      {view==='recipes' && selected && <RecipeDetail recipe={recipes.find(r=>r.recipe_id===selected)} back={()=>setSelected(null)} add={()=>{setPlannerPick({recipe:selected});setView('planner')}}/>}
      {view==='new' && <RecipeForm save={(r,immediate)=>{setUserRecipes(x=>[...x,r]); if(immediate){const d=new Date(`${r.planDate}T12:00:00`);assign(d,r.planSlot,r.recipe_id);setWeek(localDate(mondayOf(d)));setView('planner')}else{setView('recipes');setSelected(r.recipe_id)}}} cancel={()=>navigate('recipes')}/>}
      {view==='planner' && <Planner recipes={recipes} dates={weekDates} week={week} plan={plan} shift={shiftWeek} pick={plannerPick} setPick={setPlannerPick} assign={assign} remove={(d,s)=>assign(d,s,null)} />}
      {view==='shopping' && <Shopping recipes={recipes} plan={plan} dates={weekDates} week={week} checked={checked} setChecked={setChecked} pantry={pantry} setPantry={setPantry} shift={shiftWeek}/>}
    </main>
  </div>
}

function Catalog({recipes,search,setSearch,open,add}) {
  const [filter,setFilter]=useState('All')
  const shown=recipes.filter(r=>(filter==='All'||r.mealType===filter)&&(`${r.title} ${r.short_description} ${idName(lookups.cuisines,r.cuisine,'cuisine_id','cuisine_name')}`).toLowerCase().includes(search.toLowerCase()))
  return <div className="page catalog"><div className="eyebrow">YOUR KITCHEN LIBRARY</div><div className="title-row"><div><h1>Recipes</h1><p>Good food, gathered in one place.</p></div><button className="primary" onClick={add}><Icon name="plus"/> Add recipe</button></div>
    <div className="catalog-tools"><div className="search"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search your recipes..."/></div><div className="pills">{['All',...lookups.mealTypes.slice(0,4).map(x=>x.meal_type_id)].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x==='All'?'All recipes':idName(lookups.mealTypes,x,'meal_type_id','meal_type_name')}</button>)}</div></div>
    <div className="recipe-grid">{shown.map(r=><article className="recipe-card" key={r.recipe_id} onClick={()=>open(r.recipe_id)}><div className="card-image" style={{'--accent':r.accent}}><img src={r.image||APPROVED_IMAGES.placeholder} onError={e=>{e.currentTarget.src=APPROVED_IMAGES.placeholder}}/><span className="meal-badge">{idName(lookups.mealTypes,r.mealType,'meal_type_id','meal_type_name')}</span><button className="round-more"><Icon name="more"/></button></div><div className="card-body"><div className="card-meta"><span>{idName(lookups.cuisines,r.cuisine,'cuisine_id','cuisine_name')}</span><span className="dot">•</span><span>{r.categories.slice(0,1).map(x=>idName(lookups.categories,x,'category_id','category_name'))}</span></div><h2>{r.title}</h2><p>{r.short_description}</p><div className="stats"><span><Icon name="clock"/>{r.prep+r.cook} min</span><span><Icon name="users"/>{r.servings} servings</span><span className="spice"><Icon name="flame"/> {r.spice}/5</span></div></div></article>)}</div>
    {!shown.length&&<div className="empty"><h2>No recipes found</h2><p>Try another search or add a recipe of your own.</p></div>}
  </div>
}

function RecipeDetail({recipe,back,add}) { if(!recipe)return null; return <div className="detail"><button className="back" onClick={back}><Icon name="arrow"/> Back to recipes</button><div className="detail-hero"><img src={recipe.image||APPROVED_IMAGES.placeholder} onError={e=>e.currentTarget.src=APPROVED_IMAGES.placeholder}/><div className="detail-overlay"></div><div className="detail-title"><span className="meal-badge">{idName(lookups.cuisines,recipe.cuisine,'cuisine_id','cuisine_name')}</span><h1>{recipe.title}</h1><p>{recipe.short_description}</p><div className="hero-stats"><span><b>{recipe.prep}</b> min prep</span><span><b>{recipe.cook}</b> min cook</span><span><b>{recipe.servings}</b> servings</span></div></div></div>
  <div className="detail-grid"><section><div className="section-heading"><div><span className="section-number">01</span><h2>Ingredients</h2></div><span>{recipe.servings} servings</span></div>{[...new Set(recipe.ingredients.map(i=>i.section_name||'Main'))].map(sec=><div className="ingredient-section" key={sec}><h3>{sec}</h3>{recipe.ingredients.filter(i=>(i.section_name||'Main')===sec).map((i,n)=><div className="ingredient-line" key={n}><span className="check-circle"></span><span><b>{i.quantity} {i.unit}</b> {i.ingredient_name}{i.optional&&<em> optional</em>}</span></div>)}</div>)}</section>
  <section><div className="section-heading"><div><span className="section-number">02</span><h2>Method</h2></div></div>{recipe.steps.map((s,i)=><div className="method-step" key={i}><span>{String(i+1).padStart(2,'0')}</span><div><p>{s.text}</p>{s.timer>0&&<small><Icon name="clock"/> {s.timer} minutes</small>}</div></div>)}</section></div><div className="sticky-add"><div><span>Ready to make it?</span><b>Add this recipe to your week</b></div><button className="primary" onClick={add}><Icon name="calendar"/> Add to meal plan</button></div></div> }

const blankIngredient=()=>({section_name:'Main',ingredient_id:'',ingredient_name:'',quantity:'',unit:'cup',optional:false})
function RecipeForm({save,cancel}) {
 const [f,setF]=useState({title:'',source_url:'',short_description:'',cuisine:'CU01',mealType:'MT03',dietary:[],categories:[],servings:4,prep:15,cook:30,spice:2,image:'',accent:colors[0],ingredients:[blankIngredient()],steps:[{text:'',timer:0}],includeSuggestions:true,includeShopping:true,showNutrition:false,substitutions:true,measurement:'US',immediate:false,planDate:localDate(new Date()),planSlot:'Dinner'})
 const [options,setOptions]=useState(false); const update=(k,v)=>setF(x=>({...x,[k]:v})); const toggle=(k,v)=>update(k,f[k].includes(v)?f[k].filter(x=>x!==v):[...f[k],v])
 const submit=e=>{e.preventDefault(); if(!f.title.trim())return; const r={...f,recipe_id:`USR-${Date.now()}`,title:f.title.trim(),image:f.image.trim(),ingredients:f.ingredients.filter(i=>i.ingredient_id||i.ingredient_name).map(i=>({...i,ingredient_name:i.ingredient_name||idName(lookups.ingredients,i.ingredient_id,'ingredient_id','ingredient_name')})),steps:f.steps.filter(s=>s.text.trim())}; save(r,f.immediate)}
 const mutate=(key,i,field,val)=>update(key,f[key].map((x,n)=>n===i?{...x,[field]:val}:x)); const move=(key,i,dir)=>{const a=[...f[key]],j=i+dir;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];update(key,a)}
 return <form className="page form-page" onSubmit={submit}><button type="button" className="back" onClick={cancel}><Icon name="arrow"/> Recipes</button><div className="form-header"><div><div className="eyebrow">ADD TO YOUR COLLECTION</div><h1>Create a recipe</h1><p>Capture something delicious. You can refine it anytime.</p></div><div className="form-actions"><button type="button" className="secondary" onClick={cancel}>Cancel</button><button className="primary">Save recipe</button></div></div>
 <FormSection n="01" title="Recipe details" subtitle="Start with the essentials."><div className="field wide"><label>Recipe title *</label><input required value={f.title} onChange={e=>update('title',e.target.value)} placeholder="e.g. Sunday lemon roast chicken"/></div><div className="field wide"><label>Short description</label><textarea rows="2" value={f.short_description} onChange={e=>update('short_description',e.target.value)} placeholder="A quick note about what makes this special..."/></div><div className="field"><label>Source link</label><input type="url" value={f.source_url} onChange={e=>update('source_url',e.target.value)} placeholder="https://"/></div><div className="field"><label>Cuisine</label><Select list={lookups.cuisines} id="cuisine_id" name="cuisine_name" value={f.cuisine} onChange={v=>update('cuisine',v)}/></div><div className="field"><label>Primary meal type</label><Select list={lookups.mealTypes} id="meal_type_id" name="meal_type_name" value={f.mealType} onChange={v=>update('mealType',v)}/></div><div className="field wide"><label>Dietary suitability</label><ChipSelect list={lookups.dietary} id="dietary_tag_id" name="dietary_tag_name" selected={f.dietary} toggle={v=>toggle('dietary',v)}/></div><div className="field wide"><label>Recipe categories</label><ChipSelect list={lookups.categories} id="category_id" name="category_name" selected={f.categories} toggle={v=>toggle('categories',v)}/></div></FormSection>
 <FormSection n="02" title="Timing & yield" subtitle="Help future you plan ahead."><div className="field"><label>Servings</label><div className="stepper"><button type="button" onClick={()=>update('servings',Math.max(1,f.servings-1))}>−</button><b>{f.servings}</b><button type="button" onClick={()=>update('servings',f.servings+1)}>+</button></div></div><div className="field"><label>Prep time <span>minutes</span></label><input type="number" min="0" value={f.prep} onChange={e=>update('prep',+e.target.value)}/></div><div className="field"><label>Cook time <span>minutes</span></label><input type="number" min="0" value={f.cook} onChange={e=>update('cook',+e.target.value)}/></div><div className="field total"><label>Total time</label><strong>{f.prep+f.cook} min</strong></div><div className="field wide spice-control"><label>Spice level <span>{['Mild','Gentle','Medium','Hot','Very hot','Fiery'][f.spice]}</span></label><input type="range" min="0" max="5" value={f.spice} onChange={e=>update('spice',+e.target.value)}/><div className="range-label"><span>Mild</span><span>Very spicy</span></div></div></FormSection>
 <FormSection n="03" title="Image & appearance" subtitle="Give your recipe a little personality."><div className="field wide"><label>Cover image URL</label><div className="upload"><Icon name="upload" size={26}/><div><b>Paste an approved image URL</b><span>Leave empty to use the kitchen placeholder</span></div><input value={f.image} onChange={e=>update('image',e.target.value)} placeholder="https://..."/></div></div><div className="field wide"><label>Card accent</label><div className="color-row">{colors.map(c=><button type="button" aria-label={c} key={c} style={{background:c}} className={f.accent===c?'selected':''} onClick={()=>update('accent',c)}>{f.accent===c&&<Icon name="check"/>}</button>)}</div></div></FormSection>
 <FormSection n="04" title="Ingredients" subtitle="Group ingredients into helpful sections."><div className="repeat-list">{f.ingredients.map((ing,i)=><div className="ingredient-row" key={i}><div className="reorder"><button type="button" onClick={()=>move('ingredients',i,-1)}>↑</button><button type="button" onClick={()=>move('ingredients',i,1)}>↓</button></div><input className="section-input" value={ing.section_name} onChange={e=>mutate('ingredients',i,'section_name',e.target.value)} placeholder="Section"/><div className="ingredient-search"><input list="ingredients-list" value={ing.ingredient_name} onChange={e=>{const found=lookups.ingredients.find(x=>x.ingredient_name===e.target.value);mutate('ingredients',i,'ingredient_name',e.target.value);if(found)mutate('ingredients',i,'ingredient_id',found.ingredient_id)}} placeholder="Search ingredient..."/></div><input type="number" min="0" step="any" value={ing.quantity} onChange={e=>mutate('ingredients',i,'quantity',e.target.value)} placeholder="Qty"/><select value={ing.unit} onChange={e=>mutate('ingredients',i,'unit',e.target.value)}>{lookups.units.map(u=><option key={u.unit_id}>{u.unit_name}</option>)}</select><label className="mini-check"><input type="checkbox" checked={ing.optional} onChange={e=>mutate('ingredients',i,'optional',e.target.checked)}/> Optional</label><button type="button" className="icon-button" onClick={()=>update('ingredients',f.ingredients.filter((_,n)=>n!==i))}><Icon name="trash"/></button></div>)}</div><datalist id="ingredients-list">{lookups.ingredients.map(i=><option key={i.ingredient_id}>{i.ingredient_name}</option>)}</datalist><div className="add-row"><button type="button" onClick={()=>update('ingredients',[...f.ingredients,{...blankIngredient(),section_name:f.ingredients.at(-1)?.section_name||'Main'}])}><Icon name="plus"/> Add ingredient</button><button type="button" onClick={()=>update('ingredients',[...f.ingredients,{...blankIngredient(),section_name:'New section'}])}><Icon name="plus"/> Add section</button></div></FormSection>
 <FormSection n="05" title="Method" subtitle="Write the path from prep to plate."><div className="steps-list">{f.steps.map((s,i)=><div className="step-edit" key={i}><span className="step-num">{i+1}</span><textarea value={s.text} onChange={e=>mutate('steps',i,'text',e.target.value)} placeholder="Describe this step..."/><div className="timer-field"><Icon name="clock"/><input type="number" min="0" value={s.timer} onChange={e=>mutate('steps',i,'timer',+e.target.value)}/><span>min</span></div><div className="step-buttons"><button type="button" onClick={()=>move('steps',i,-1)}>↑</button><button type="button" onClick={()=>move('steps',i,1)}>↓</button><button type="button" onClick={()=>update('steps',f.steps.filter((_,n)=>n!==i))}><Icon name="trash"/></button></div></div>)}</div><button type="button" className="add-outline" onClick={()=>update('steps',[...f.steps,{text:'',timer:0}])}><Icon name="plus"/> Add method step</button></FormSection>
 <FormSection n="06" title="Meal planning" subtitle="Put this recipe to work in your week."><Toggle label="Include in meal-plan suggestions" note="This recipe can appear when choosing a meal." checked={f.includeSuggestions} set={v=>update('includeSuggestions',v)}/><Toggle label="Add to meal plan now" note="Schedule it as soon as the recipe is saved." checked={f.immediate} set={v=>update('immediate',v)}/>{f.immediate&&<div className="plan-fields"><div className="field"><label>Cooking date</label><input type="date" value={f.planDate} onChange={e=>update('planDate',e.target.value)}/></div><div className="field"><label>Serving time</label><select value={f.planSlot} onChange={e=>update('planSlot',e.target.value)}>{slots.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Specific time <span>optional</span></label><input type="time" onChange={e=>update('planTime',e.target.value)}/></div></div>}</FormSection>
 <div className="options-wrap"><button type="button" className="options-button" onClick={()=>setOptions(!options)}><span><Icon name="sliders"/><span><b>Recipe options</b><small>Shopping, nutrition & measurements</small></span></span><Icon name="chevron"/></button>{options&&<div className="options-menu"><Toggle label="Include ingredients in shopping lists" checked={f.includeShopping} set={v=>update('includeShopping',v)}/><Toggle label="Show nutrition information" checked={f.showNutrition} set={v=>update('showNutrition',v)}/><Toggle label="Allow ingredient substitutions" checked={f.substitutions} set={v=>update('substitutions',v)}/><div className="measurement"><label>Measurements</label><div><button type="button" className={f.measurement==='US'?'active':''} onClick={()=>update('measurement','US')}>US customary</button><button type="button" className={f.measurement==='Metric'?'active':''} onClick={()=>update('measurement','Metric')}>Metric</button></div></div></div>}</div><div className="bottom-save"><button type="button" className="secondary" onClick={cancel}>Cancel</button><button className="primary">Save recipe</button></div></form>
}

function FormSection({n,title,subtitle,children}){return <section className="form-section"><div className="form-section-title"><span>{n}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div><div className="form-grid">{children}</div></section>}
function Select({list,id,name,value,onChange}){return <select value={value} onChange={e=>onChange(e.target.value)}>{list.map(x=><option value={x[id]} key={x[id]}>{x[name]}</option>)}</select>}
function ChipSelect({list,id,name,selected,toggle}){return <div className="chips">{list.map(x=><button type="button" className={selected.includes(x[id])?'selected':''} onClick={()=>toggle(x[id])} key={x[id]}>{selected.includes(x[id])&&<Icon name="check" size={14}/>} {x[name]}</button>)}</div>}
function Toggle({label,note,checked,set}){return <div className="toggle-row"><div><b>{label}</b>{note&&<small>{note}</small>}</div><button type="button" className={`toggle ${checked?'on':''}`} onClick={()=>set(!checked)}><span></span></button></div>}

function Planner({recipes,dates,week,plan,shift,pick,setPick,assign,remove}) {
 const range=`${dates[0].toLocaleDateString('en-US',{month:'long',day:'numeric'})} – ${dates[6].toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}`
 return <div className="page planner"><div className="eyebrow">YOUR WEEK AT A GLANCE</div><div className="title-row"><div><h1>Meal planner</h1><p>A little intention makes the week taste better.</p></div><div className="week-nav"><button onClick={()=>shift(-1)}><Icon name="arrow"/></button><b>{range}</b><button className="next" onClick={()=>shift(1)}><Icon name="arrow"/></button></div></div>
 <div className="calendar-grid"><div className="corner"></div>{dates.map((d,i)=><div className={`day-head ${localDate(d)===localDate(new Date())?'today':''}`} key={i}><span>{days[i]}</span><b>{d.getDate()}</b></div>)}{slots.map(slot=><div className="calendar-row" key={slot}><div className="slot-label"><span>{slot}</span></div>{dates.map(d=>{const key=`${localDate(d)}|${slot}`,r=recipes.find(x=>x.recipe_id===plan[key]);return <div className="meal-cell" key={key}>{r?<div className="planned" style={{'--accent':r.accent}}><div><small>{idName(lookups.cuisines,r.cuisine,'cuisine_id','cuisine_name')}</small><b>{r.title}</b><span>{r.prep+r.cook} min</span></div><button onClick={()=>setPick({date:d,slot,current:r.recipe_id})}><Icon name="more"/></button></div>:<button className="add-meal" onClick={()=>setPick({date:d,slot})}><Icon name="plus"/><span>Add meal</span></button>}</div>})}</div>)}</div>
 {pick&&<RecipePicker recipes={recipes} pick={pick} close={()=>setPick(null)} assign={assign} remove={remove}/>}</div>
}
function RecipePicker({recipes,pick,close,assign,remove}){const [q,setQ]=useState('');const shown=recipes.filter(r=>r.includeSuggestions!==false&&r.title.toLowerCase().includes(q.toLowerCase()));return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><div><span>{pick.date?`${days[(pick.date.getDay()+6)%7]}, ${pick.date.toLocaleDateString('en-US',{month:'short',day:'numeric'})}`:'Choose a slot'}</span><h2>{pick.current?'Replace meal':'Choose a recipe'} · {pick.slot}</h2></div><button onClick={close}><Icon name="close"/></button></div><div className="modal-search search"><Icon name="search"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search recipes..."/></div><div className="picker-list">{shown.map(r=><button key={r.recipe_id} onClick={()=>assign(pick.date,pick.slot,r.recipe_id)}><img src={r.image||APPROVED_IMAGES.placeholder} onError={e=>e.currentTarget.src=APPROVED_IMAGES.placeholder}/><span><b>{r.title}</b><small>{idName(lookups.cuisines,r.cuisine,'cuisine_id','cuisine_name')} · {r.prep+r.cook} min</small></span><Icon name="chevron"/></button>)}</div>{pick.current&&<button className="remove-meal" onClick={()=>{remove(pick.date,pick.slot);close()}}><Icon name="trash"/> Remove from plan</button>}</div></div>}

function Shopping({recipes,plan,dates,checked,setChecked,pantry,setPantry,shift}){
 const keys=new Set(dates.flatMap(d=>slots.map(s=>plan[`${localDate(d)}|${s}`]).filter(Boolean))); const planned=recipes.filter(r=>keys.has(r.recipe_id)&&r.includeShopping!==false)
 const grouped={}; planned.flatMap(r=>r.ingredients.filter(i=>!i.optional)).forEach(i=>{const ing=lookups.ingredients.find(x=>x.ingredient_id===i.ingredient_id)||lookups.ingredients.find(x=>x.ingredient_name.toLowerCase()===i.ingredient_name.toLowerCase()); const cat=ing?.shopping_category||'Grains & pantry', k=`${i.ingredient_name}|${i.unit}`; if(!grouped[cat])grouped[cat]={}; if(!grouped[cat][k])grouped[cat][k]={name:i.ingredient_name,unit:i.unit,quantity:0}; grouped[cat][k].quantity+=(+i.quantity||0)})
 const all=Object.values(grouped).flatMap(x=>Object.values(x)), done=all.filter(i=>checked[`${week}|${i.name}|${i.unit}`]).length
 const range=`${dates[0].toLocaleDateString('en-US',{month:'short',day:'numeric'})} – ${dates[6].toLocaleDateString('en-US',{month:'short',day:'numeric'})}`
 return <div className="page shopping"><div className="eyebrow">FROM PLAN TO PANTRY</div><div className="title-row"><div><h1>Shopping list</h1><p>Everything you need, gathered from this week’s meals.</p></div><div className="week-nav compact"><button onClick={()=>shift(-1)}><Icon name="arrow"/></button><b>{range}</b><button className="next" onClick={()=>shift(1)}><Icon name="arrow"/></button></div></div>
 <div className="shopping-summary"><div className="bag"><Icon name="cart" size={28}/></div><div><b>{all.length-done} items left</b><span>From {planned.length} planned recipe{planned.length===1?'':'s'}</span></div><div className="progress"><span style={{width:`${all.length?done/all.length*100:0}%`}}></span></div><small>{done} of {all.length} collected</small></div>
 {!all.length?<div className="empty illustrated"><div className="empty-icon"><Icon name="cart" size={40}/></div><h2>Your list is ready for a plan</h2><p>Add recipes to this week’s meal planner and their ingredients will appear here automatically.</p></div>:<div className="shopping-layout"><div className="shopping-groups">{Object.entries(grouped).map(([cat,items])=><section className="shopping-group" key={cat}><h2>{cat}<span>{Object.keys(items).length}</span></h2>{Object.values(items).map(i=>{const k=`${week}|${i.name}|${i.unit}`,isDone=checked[k],has=pantry[i.name];return <div className={`shop-item ${isDone||has?'done':''}`} key={k}><button className="item-check" onClick={()=>setChecked(x=>({...x,[k]:!x[k]}))}>{isDone&&<Icon name="check" size={14}/>}</button><span><b>{i.name}</b><small>{Number(i.quantity.toFixed(2))} {i.unit}</small></span><label className="pantry-label"><input type="checkbox" checked={!!has} onChange={e=>setPantry(x=>({...x,[i.name]:e.target.checked}))}/> In pantry</label></div>})}</section>)}</div><aside><h3>This week’s recipes</h3>{planned.map(r=><div className="aside-recipe" key={r.recipe_id}><span style={{background:r.accent}}></span><div><b>{r.title}</b><small>{r.ingredients.filter(i=>!i.optional).length} ingredients</small></div></div>)}<p>Checked pantry items remain excluded across weeks.</p></aside></div>}</div>
}

export default App
